seed: 0
device: cpu

env:
  name: Hopper-v4
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  num_workers: 1

algo:
  dataset: hopper-expert-v2
  num_expert_trajs: 20

  hidden_dims: [256, 256, 256]
  activation: "silu"
  l2_penalty: 0.
  batch_size: 256
  lr_actor: 3.e-4
  grad_clip: 1000.

  train_ratio: 0.9
  max_eps_steps: 1000
  epochs: 200
  steps_per_epoch: 1000
  num_eval_eps: 1
  eval_steps: 1000

  save_path: ../../exp/il/bc/hopper-expert-v2
  save_steps: 1

logger:
  backend: wandb
  log_dir: ../../log
  project_name: cleanil_bc_hopper
  group_name: null
  exp_name: expert
  wandb_mode: online