seed: 0
device: cpu

env:
  name: Walker2d-v4
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  num_workers: 1

dynamics:
  ensemble_dim: 7
  topk: 5
  hidden_dims: [200, 200, 200]
  activation: silu
  min_std: 0.04
  max_std: 1.6
  decays: [0.000025, 0.00005, 0.000075, 0.000075, 0.0001]

algo:
  rollout_batch_size: 100000
  rollout_min_steps: 1
  rollout_max_steps: 15
  rollout_min_epoch: 20
  rollout_max_epoch: 100
  model_retain_epochs: 5
  
  lr_model: 3.e-4
  model_eval_ratio: 0.2
  model_train_samples: 100000
  model_train_batch_size: 256
  model_train_steps: 200
  update_model_every: 250
  model_retain_epochs: 5

  hidden_dims: [256, 256, 256]
  activation: "silu"
  gamma: 0.99
  polyak: 0.995
  alpha: 1.
  tune_alpha: true
  batch_size: 256
  real_ratio: 0.5
  policy_train_steps: 10
  update_policy_every: 1
  lr_actor: 3.e-4
  lr_critic: 3.e-4
  grad_clip: 1000.

  buffer_size: 1000000
  max_eps_steps: 1000
  epochs: 1000
  steps_per_epoch: 1000
  update_after: 2000
  num_eval_eps: 1
  eval_steps: 1000

  save_path: ../../exp/rl/mbpo/Walker2d-v4
  save_steps: 1

logger:
  backend: wandb
  log_dir: ../../log
  project_name: cleanil_mbpo_walker2d
  group_name: null
  exp_name: mbpo
  wandb_mode: online