seed: 0
device: cpu

env:
  name: Hopper-v4
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  num_workers: 1

algo:
  dataset: hopper-expert-v2
  num_expert_trajs: 20
  train_ratio: 0.9
  
  actor_loss: "awr"
  action_mask_noise: 0.1
  grad_target: 1.
  grad_penalty: 10.
  l2_penalty: 0.
  td_penalty: 0.5

  hidden_dims: [256, 256, 256]
  activation: "silu"
  gamma: 0.99
  polyak: 0.995
  alpha: 0.1
  tune_alpha: false
  batch_size: 256
  policy_train_steps: 1
  lr_actor: 3.e-4
  lr_critic: 3.e-4
  grad_clip: 1000.

  buffer_size: 1000000
  max_eps_steps: 1000
  epochs: 500
  steps_per_epoch: 1000
  num_eval_eps: 1
  eval_steps: 1000

  save_path: ../../exp/il/iqlearn/hopper-expert-v2
  save_steps: 1

logger:
  backend: wandb
  log_dir: ../../log
  project_name: cleanil_iqlearn_hopper
  group_name: null
  exp_name: expert
  wandb_mode: online