seed: 0
device: cuda

algo:
  dataset: "experimenting with choice data/final/aguirregabiria_mira.pkl"
  load_local_csv: True
  id_ : 'id'
  num_expert_trajs: 104
  train_ratio: 0.9

    
  obs_dim : 6
  act_dim : 1
  num_actions: 2

  sequential: True
  SEQUENCE_LENGTH: 2
  model: 'lstm'



  
  
  actor_loss: "awr"
  action_mask_noise: 0.1
  grad_target: 1.
  grad_penalty: 10.
  l2_penalty: 0.
  td_penalty: 0.5
  
  bc_penalty: 0.01 
  temperature: 0.1

  hidden_dims: [256,64]
  activation: "silu"
  gamma: 0.99
  polyak: 0.995
  alpha: 0.1
  dropout: 0.05
  tune_alpha: false
  batch_size: 256
  policy_train_steps: 1
  lr_actor: 3.e-4
  lr_critic: 5.e-4
  grad_clip: 1000.

  epochs: 1000
  steps_per_epoch: 1000
  num_eval_eps: 0

  save_path: ./exp/offline_rust_discrete_lstm_v1
  save_steps: 50

logger:
  backend: wandb
  log_dir: ./log
  project_name: offline_iqlearn_rust_discrete_lstm
  group_name: null
  exp_name: rust_discrete_offline_lstm_v1
  wandb_mode: online
