seed: 0
device: cuda

algo:
  dataset: "NathanGavenski/LunarLander-v2"
  load_local_csv: False
  num_expert_trajs: 1000
  train_ratio: 0.9

    
  obs_dim : 8
  act_dim : 1
  num_actions: 4

  
  
  actor_loss: "awr"
  action_mask_noise: 0.1
  grad_target: 1.
  grad_penalty: 10.
  l2_penalty: 0.
  td_penalty: 0.5

  bc_penalty: 0.01 

  temperature: 0.1
  

  hidden_dims: [256, 256, 256]
  activation: "silu"
  gamma: 0.99
  polyak: 0.995
  dropout: 0.0
  alpha: 0.1
  tune_alpha: false
  batch_size: 256
  policy_train_steps: 1
  lr_actor: 3.e-4
  lr_critic: 3.e-5
  grad_clip: 1000.

  epochs: 500
  steps_per_epoch: 500
  num_eval_eps: 0

  save_path: ./exp/offline_lunarlander_discrete_v2
  save_steps: 50

logger:
  backend: wandb
  log_dir: ./log
  project_name: offline_iqlearn_lunarlander_discrete
  group_name: null
  exp_name: lunarlander_discrete_offline_v2
  wandb_mode: online
